USE premium_store;

-- Seed/update the bundled product artwork for existing installations.
UPDATE products SET main_image='assets/images/products/linen-shirt.jpg', secondary_image='assets/images/products/linen-shirt.jpg' WHERE name='Linen Tailored Shirt';
UPDATE products SET main_image='assets/images/products/headphones.jpg', secondary_image='assets/images/products/headphones.jpg' WHERE name='Premium Wireless Headphones';
UPDATE products SET main_image='assets/images/products/sneakers.jpg', secondary_image='assets/images/products/sneakers.jpg' WHERE name='Minimal Leather Sneakers';
UPDATE products SET main_image='assets/images/products/mini-bag.jpg', secondary_image='assets/images/products/mini-bag.jpg' WHERE name='Structured Mini Bag';
UPDATE products SET main_image='assets/images/products/skin-set.jpg', secondary_image='assets/images/products/skin-set.jpg' WHERE name='Signature Skin Set';
UPDATE products SET main_image='assets/images/products/table-lamp.jpg', secondary_image='assets/images/products/table-lamp.jpg' WHERE name='Ceramic Table Lamp';

-- Keep the low-stock threshold configurable.
INSERT INTO site_settings(setting_key,setting_value) VALUES ('low_stock_threshold','5')
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);

-- LUXORA expanded catalog upgrade
INSERT INTO categories(name,description) VALUES
('Watches','Premium timepieces for every occasion'),
('Caps & Accessories','Finishing touches and everyday accessories'),
('Sports','Performance and recreation essentials')
ON DUPLICATE KEY UPDATE description=VALUES(description);

INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Oversized T-Shirt','Premium Oversized T-Shirt crafted for modern everyday use with a premium LUXORA finish.',49.00,10,35,4.7,92,'assets/images/products/premium-oversized-t-shirt.jpg','assets/images/products/premium-oversized-t-shirt.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Oversized T-Shirt') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Classic Cotton Shirt','Classic Cotton Shirt crafted for modern everyday use with a premium LUXORA finish.',59.00,0,28,4.6,74,'assets/images/products/classic-cotton-shirt.jpg','assets/images/products/classic-cotton-shirt.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Classic Cotton Shirt') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Casual Hoodie','Casual Hoodie crafted for modern everyday use with a premium LUXORA finish.',69.00,15,22,4.8,108,'assets/images/products/casual-hoodie.jpg','assets/images/products/casual-hoodie.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Casual Hoodie') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Polo Shirt','Premium Polo Shirt crafted for modern everyday use with a premium LUXORA finish.',54.00,10,31,4.7,81,'assets/images/products/premium-polo-shirt.jpg','assets/images/products/premium-polo-shirt.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Polo Shirt') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Relaxed Fit Jeans','Relaxed Fit Jeans crafted for modern everyday use with a premium LUXORA finish.',79.00,12,19,4.6,67,'assets/images/products/relaxed-fit-jeans.jpg','assets/images/products/relaxed-fit-jeans.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Relaxed Fit Jeans') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Cargo Pants','Cargo Pants crafted for modern everyday use with a premium LUXORA finish.',72.00,0,17,4.5,53,'assets/images/products/cargo-pants.jpg','assets/images/products/cargo-pants.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Cargo Pants') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Denim Jacket','Denim Jacket crafted for modern everyday use with a premium LUXORA finish.',99.00,15,12,4.8,46,'assets/images/products/denim-jacket.jpg','assets/images/products/denim-jacket.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Denim Jacket') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Sports Tracksuit','Sports Tracksuit crafted for modern everyday use with a premium LUXORA finish.',89.00,10,16,4.6,39,'assets/images/products/sports-tracksuit.jpg','assets/images/products/sports-tracksuit.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Sports Tracksuit') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Casual Shorts','Casual Shorts crafted for modern everyday use with a premium LUXORA finish.',42.00,0,30,4.5,51,'assets/images/products/casual-shorts.jpg','assets/images/products/casual-shorts.jpg','active' FROM categories c WHERE c.name='Fashion' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Casual Shorts') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Classic Leather Watch','Classic Leather Watch crafted for modern everyday use with a premium LUXORA finish.',129.00,10,14,4.9,132,'assets/images/products/classic-leather-watch.jpg','assets/images/products/classic-leather-watch.jpg','active' FROM categories c WHERE c.name='Watches' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Classic Leather Watch') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Steel Watch','Premium Steel Watch crafted for modern everyday use with a premium LUXORA finish.',159.00,15,11,4.8,94,'assets/images/products/premium-steel-watch.jpg','assets/images/products/premium-steel-watch.jpg','active' FROM categories c WHERE c.name='Watches' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Steel Watch') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Minimal Black Watch','Minimal Black Watch crafted for modern everyday use with a premium LUXORA finish.',119.00,0,20,4.7,77,'assets/images/products/minimal-black-watch.jpg','assets/images/products/minimal-black-watch.jpg','active' FROM categories c WHERE c.name='Watches' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Minimal Black Watch') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Chronograph Watch','Chronograph Watch crafted for modern everyday use with a premium LUXORA finish.',189.00,20,8,4.9,61,'assets/images/products/chronograph-watch.jpg','assets/images/products/chronograph-watch.jpg','active' FROM categories c WHERE c.name='Watches' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Chronograph Watch') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Sport Digital Watch','Sport Digital Watch crafted for modern everyday use with a premium LUXORA finish.',89.00,5,24,4.6,58,'assets/images/products/sport-digital-watch.jpg','assets/images/products/sport-digital-watch.jpg','active' FROM categories c WHERE c.name='Watches' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Sport Digital Watch') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Luxury Style Watch','Luxury Style Watch crafted for modern everyday use with a premium LUXORA finish.',219.00,18,6,4.9,43,'assets/images/products/luxury-style-watch.jpg','assets/images/products/luxury-style-watch.jpg','active' FROM categories c WHERE c.name='Watches' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Luxury Style Watch') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Classic Black Cap','Classic Black Cap crafted for modern everyday use with a premium LUXORA finish.',29.00,0,40,4.7,119,'assets/images/products/classic-black-cap.jpg','assets/images/products/classic-black-cap.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Classic Black Cap') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Baseball Cap','Premium Baseball Cap crafted for modern everyday use with a premium LUXORA finish.',34.00,10,26,4.8,86,'assets/images/products/premium-baseball-cap.jpg','assets/images/products/premium-baseball-cap.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Baseball Cap') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Minimal Logo Cap','Minimal Logo Cap crafted for modern everyday use with a premium LUXORA finish.',31.00,5,32,4.6,62,'assets/images/products/minimal-logo-cap.jpg','assets/images/products/minimal-logo-cap.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Minimal Logo Cap') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Vintage Sports Cap','Vintage Sports Cap crafted for modern everyday use with a premium LUXORA finish.',36.00,12,18,4.7,48,'assets/images/products/vintage-sports-cap.jpg','assets/images/products/vintage-sports-cap.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Vintage Sports Cap') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Cotton Snapback','Cotton Snapback crafted for modern everyday use with a premium LUXORA finish.',39.00,0,21,4.8,57,'assets/images/products/cotton-snapback.jpg','assets/images/products/cotton-snapback.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Cotton Snapback') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Sunglasses','Premium Sunglasses crafted for modern everyday use with a premium LUXORA finish.',69.00,15,15,4.6,72,'assets/images/products/premium-sunglasses.jpg','assets/images/products/premium-sunglasses.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Sunglasses') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Leather Wallet','Leather Wallet crafted for modern everyday use with a premium LUXORA finish.',45.00,0,25,4.8,88,'assets/images/products/leather-wallet.jpg','assets/images/products/leather-wallet.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Leather Wallet') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Minimal Belt','Minimal Belt crafted for modern everyday use with a premium LUXORA finish.',38.00,5,27,4.6,49,'assets/images/products/minimal-belt.jpg','assets/images/products/minimal-belt.jpg','active' FROM categories c WHERE c.name='Caps & Accessories' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Minimal Belt') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Professional Cricket Bat','Professional Cricket Bat crafted for modern everyday use with a premium LUXORA finish.',139.00,10,9,4.9,73,'assets/images/products/professional-cricket-bat.jpg','assets/images/products/professional-cricket-bat.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Professional Cricket Bat') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Tennis Ball Set','Tennis Ball Set crafted for modern everyday use with a premium LUXORA finish.',24.00,0,45,4.6,34,'assets/images/products/tennis-ball-set.jpg','assets/images/products/tennis-ball-set.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Tennis Ball Set') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Cricket Ball','Premium Cricket Ball crafted for modern everyday use with a premium LUXORA finish.',19.00,0,50,4.7,41,'assets/images/products/premium-cricket-ball.jpg','assets/images/products/premium-cricket-ball.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Cricket Ball') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Match Football','Match Football crafted for modern everyday use with a premium LUXORA finish.',49.00,12,20,4.8,64,'assets/images/products/match-football.jpg','assets/images/products/match-football.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Match Football') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Pro Basketball','Pro Basketball crafted for modern everyday use with a premium LUXORA finish.',44.00,5,18,4.7,38,'assets/images/products/pro-basketball.jpg','assets/images/products/pro-basketball.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Pro Basketball') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Training Football','Training Football crafted for modern everyday use with a premium LUXORA finish.',35.00,0,26,4.5,29,'assets/images/products/training-football.jpg','assets/images/products/training-football.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Training Football') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Sports Water Bottle','Sports Water Bottle crafted for modern everyday use with a premium LUXORA finish.',27.00,10,34,4.8,91,'assets/images/products/sports-water-bottle.jpg','assets/images/products/sports-water-bottle.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Sports Water Bottle') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Gym Gloves','Gym Gloves crafted for modern everyday use with a premium LUXORA finish.',22.00,0,29,4.6,47,'assets/images/products/gym-gloves.jpg','assets/images/products/gym-gloves.jpg','active' FROM categories c WHERE c.name='Sports' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Gym Gloves') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Running Shoes','Running Shoes crafted for modern everyday use with a premium LUXORA finish.',109.00,15,13,4.8,112,'assets/images/products/running-shoes.jpg','assets/images/products/running-shoes.jpg','active' FROM categories c WHERE c.name='Shoes' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Running Shoes') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Casual Sneakers','Casual Sneakers crafted for modern everyday use with a premium LUXORA finish.',99.00,10,16,4.7,83,'assets/images/products/casual-sneakers.jpg','assets/images/products/casual-sneakers.jpg','active' FROM categories c WHERE c.name='Shoes' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Casual Sneakers') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Sports Trainers','Sports Trainers crafted for modern everyday use with a premium LUXORA finish.',119.00,20,10,4.8,69,'assets/images/products/sports-trainers.jpg','assets/images/products/sports-trainers.jpg','active' FROM categories c WHERE c.name='Shoes' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Sports Trainers') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Classic White Sneakers','Classic White Sneakers crafted for modern everyday use with a premium LUXORA finish.',89.00,0,23,4.7,105,'assets/images/products/classic-white-sneakers.jpg','assets/images/products/classic-white-sneakers.jpg','active' FROM categories c WHERE c.name='Shoes' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Classic White Sneakers') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Bluetooth Earbuds','Bluetooth Earbuds crafted for modern everyday use with a premium LUXORA finish.',79.00,15,18,4.7,98,'assets/images/products/bluetooth-earbuds.jpg','assets/images/products/bluetooth-earbuds.jpg','active' FROM categories c WHERE c.name='Electronics' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Bluetooth Earbuds') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Portable Speaker','Portable Speaker crafted for modern everyday use with a premium LUXORA finish.',69.00,10,14,4.6,76,'assets/images/products/portable-speaker.jpg','assets/images/products/portable-speaker.jpg','active' FROM categories c WHERE c.name='Electronics' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Portable Speaker') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Wireless Charger','Wireless Charger crafted for modern everyday use with a premium LUXORA finish.',35.00,0,33,4.5,51,'assets/images/products/wireless-charger.jpg','assets/images/products/wireless-charger.jpg','active' FROM categories c WHERE c.name='Electronics' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Wireless Charger') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Body Care Set','Premium Body Care Set crafted for modern everyday use with a premium LUXORA finish.',58.00,10,20,4.7,44,'assets/images/products/premium-body-care-set.jpg','assets/images/products/premium-body-care-set.jpg','active' FROM categories c WHERE c.name='Beauty' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Body Care Set') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Fragrance Gift Set','Fragrance Gift Set crafted for modern everyday use with a premium LUXORA finish.',75.00,15,12,4.8,63,'assets/images/products/fragrance-gift-set.jpg','assets/images/products/fragrance-gift-set.jpg','active' FROM categories c WHERE c.name='Beauty' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Fragrance Gift Set') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Premium Coffee Mug','Premium Coffee Mug crafted for modern everyday use with a premium LUXORA finish.',24.00,0,38,4.7,55,'assets/images/products/premium-coffee-mug.jpg','assets/images/products/premium-coffee-mug.jpg','active' FROM categories c WHERE c.name='Home & Lifestyle' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Premium Coffee Mug') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Scented Candle','Scented Candle crafted for modern everyday use with a premium LUXORA finish.',29.00,5,31,4.8,71,'assets/images/products/scented-candle.jpg','assets/images/products/scented-candle.jpg','active' FROM categories c WHERE c.name='Home & Lifestyle' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Scented Candle') LIMIT 1;
INSERT INTO products(category_id,name,description,price,discount,stock,rating,review_count,main_image,secondary_image,status) SELECT c.id,'Desk Organizer','Desk Organizer crafted for modern everyday use with a premium LUXORA finish.',32.00,0,24,4.5,33,'assets/images/products/desk-organizer.jpg','assets/images/products/desk-organizer.jpg','active' FROM categories c WHERE c.name='Home & Lifestyle' AND NOT EXISTS (SELECT 1 FROM products p WHERE p.name='Desk Organizer') LIMIT 1;

-- LUXORA realistic local product image migration
-- Image-only update for an existing database. No DROP, DELETE, table recreation, or product insertion.
-- Copy assets/images/products/*.jpg into the project before importing this file.

START TRANSACTION;
UPDATE products SET main_image='assets/images/products/linen-shirt.jpg', secondary_image='assets/images/products/linen-shirt-2.jpg' WHERE name='Linen Tailored Shirt';
UPDATE products SET main_image='assets/images/products/headphones.jpg', secondary_image='assets/images/products/headphones-2.jpg' WHERE name='Premium Wireless Headphones';
UPDATE products SET main_image='assets/images/products/sneakers.jpg', secondary_image='assets/images/products/sneakers-2.jpg' WHERE name='Minimal Leather Sneakers';
UPDATE products SET main_image='assets/images/products/mini-bag.jpg', secondary_image='assets/images/products/mini-bag-2.jpg' WHERE name='Structured Mini Bag';
UPDATE products SET main_image='assets/images/products/skin-set.jpg', secondary_image='assets/images/products/skin-set-2.jpg' WHERE name='Signature Skin Set';
UPDATE products SET main_image='assets/images/products/table-lamp.jpg', secondary_image='assets/images/products/table-lamp-2.jpg' WHERE name='Ceramic Table Lamp';
UPDATE products SET main_image='assets/images/products/premium-oversized-t-shirt.jpg', secondary_image='assets/images/products/premium-oversized-t-shirt-2.jpg' WHERE name='Premium Oversized T-Shirt';
UPDATE products SET main_image='assets/images/products/classic-cotton-shirt.jpg', secondary_image='assets/images/products/classic-cotton-shirt-2.jpg' WHERE name='Classic Cotton Shirt';
UPDATE products SET main_image='assets/images/products/casual-hoodie.jpg', secondary_image='assets/images/products/casual-hoodie-2.jpg' WHERE name='Casual Hoodie';
UPDATE products SET main_image='assets/images/products/premium-polo-shirt.jpg', secondary_image='assets/images/products/premium-polo-shirt-2.jpg' WHERE name='Premium Polo Shirt';
UPDATE products SET main_image='assets/images/products/relaxed-fit-jeans.jpg', secondary_image='assets/images/products/relaxed-fit-jeans-2.jpg' WHERE name='Relaxed Fit Jeans';
UPDATE products SET main_image='assets/images/products/cargo-pants.jpg', secondary_image='assets/images/products/cargo-pants-2.jpg' WHERE name='Cargo Pants';
UPDATE products SET main_image='assets/images/products/denim-jacket.jpg', secondary_image='assets/images/products/denim-jacket-2.jpg' WHERE name='Denim Jacket';
UPDATE products SET main_image='assets/images/products/sports-tracksuit.jpg', secondary_image='assets/images/products/sports-tracksuit-2.jpg' WHERE name='Sports Tracksuit';
UPDATE products SET main_image='assets/images/products/casual-shorts.jpg', secondary_image='assets/images/products/casual-shorts-2.jpg' WHERE name='Casual Shorts';
UPDATE products SET main_image='assets/images/products/classic-leather-watch.jpg', secondary_image='assets/images/products/classic-leather-watch-2.jpg' WHERE name='Classic Leather Watch';
UPDATE products SET main_image='assets/images/products/premium-steel-watch.jpg', secondary_image='assets/images/products/premium-steel-watch-2.jpg' WHERE name='Premium Steel Watch';
UPDATE products SET main_image='assets/images/products/minimal-black-watch.jpg', secondary_image='assets/images/products/minimal-black-watch-2.jpg' WHERE name='Minimal Black Watch';
UPDATE products SET main_image='assets/images/products/chronograph-watch.jpg', secondary_image='assets/images/products/chronograph-watch-2.jpg' WHERE name='Chronograph Watch';
UPDATE products SET main_image='assets/images/products/sport-digital-watch.jpg', secondary_image='assets/images/products/sport-digital-watch-2.jpg' WHERE name='Sport Digital Watch';
UPDATE products SET main_image='assets/images/products/luxury-style-watch.jpg', secondary_image='assets/images/products/luxury-style-watch-2.jpg' WHERE name='Luxury Style Watch';
UPDATE products SET main_image='assets/images/products/classic-black-cap.jpg', secondary_image='assets/images/products/classic-black-cap-2.jpg' WHERE name='Classic Black Cap';
UPDATE products SET main_image='assets/images/products/premium-baseball-cap.jpg', secondary_image='assets/images/products/premium-baseball-cap-2.jpg' WHERE name='Premium Baseball Cap';
UPDATE products SET main_image='assets/images/products/minimal-logo-cap.jpg', secondary_image='assets/images/products/minimal-logo-cap-2.jpg' WHERE name='Minimal Logo Cap';
UPDATE products SET main_image='assets/images/products/vintage-sports-cap.jpg', secondary_image='assets/images/products/vintage-sports-cap-2.jpg' WHERE name='Vintage Sports Cap';
UPDATE products SET main_image='assets/images/products/cotton-snapback.jpg', secondary_image='assets/images/products/cotton-snapback-2.jpg' WHERE name='Cotton Snapback';
UPDATE products SET main_image='assets/images/products/premium-sunglasses.jpg', secondary_image='assets/images/products/premium-sunglasses-2.jpg' WHERE name='Premium Sunglasses';
UPDATE products SET main_image='assets/images/products/leather-wallet.jpg', secondary_image='assets/images/products/leather-wallet-2.jpg' WHERE name='Leather Wallet';
UPDATE products SET main_image='assets/images/products/minimal-belt.jpg', secondary_image='assets/images/products/minimal-belt-2.jpg' WHERE name='Minimal Belt';
UPDATE products SET main_image='assets/images/products/professional-cricket-bat.jpg', secondary_image='assets/images/products/professional-cricket-bat-2.jpg' WHERE name='Professional Cricket Bat';
UPDATE products SET main_image='assets/images/products/tennis-ball-set.jpg', secondary_image='assets/images/products/tennis-ball-set-2.jpg' WHERE name='Tennis Ball Set';
UPDATE products SET main_image='assets/images/products/premium-cricket-ball.jpg', secondary_image='assets/images/products/premium-cricket-ball-2.jpg' WHERE name='Premium Cricket Ball';
UPDATE products SET main_image='assets/images/products/match-football.jpg', secondary_image='assets/images/products/match-football-2.jpg' WHERE name='Match Football';
UPDATE products SET main_image='assets/images/products/pro-basketball.jpg', secondary_image='assets/images/products/pro-basketball-2.jpg' WHERE name='Pro Basketball';
UPDATE products SET main_image='assets/images/products/training-football.jpg', secondary_image='assets/images/products/training-football-2.jpg' WHERE name='Training Football';
UPDATE products SET main_image='assets/images/products/sports-water-bottle.jpg', secondary_image='assets/images/products/sports-water-bottle-2.jpg' WHERE name='Sports Water Bottle';
UPDATE products SET main_image='assets/images/products/gym-gloves.jpg', secondary_image='assets/images/products/gym-gloves-2.jpg' WHERE name='Gym Gloves';
UPDATE products SET main_image='assets/images/products/running-shoes.jpg', secondary_image='assets/images/products/running-shoes-2.jpg' WHERE name='Running Shoes';
UPDATE products SET main_image='assets/images/products/casual-sneakers.jpg', secondary_image='assets/images/products/casual-sneakers-2.jpg' WHERE name='Casual Sneakers';
UPDATE products SET main_image='assets/images/products/sports-trainers.jpg', secondary_image='assets/images/products/sports-trainers-2.jpg' WHERE name='Sports Trainers';
UPDATE products SET main_image='assets/images/products/classic-white-sneakers.jpg', secondary_image='assets/images/products/classic-white-sneakers-2.jpg' WHERE name='Classic White Sneakers';
UPDATE products SET main_image='assets/images/products/bluetooth-earbuds.jpg', secondary_image='assets/images/products/bluetooth-earbuds-2.jpg' WHERE name='Bluetooth Earbuds';
UPDATE products SET main_image='assets/images/products/portable-speaker.jpg', secondary_image='assets/images/products/portable-speaker-2.jpg' WHERE name='Portable Speaker';
UPDATE products SET main_image='assets/images/products/wireless-charger.jpg', secondary_image='assets/images/products/wireless-charger-2.jpg' WHERE name='Wireless Charger';
UPDATE products SET main_image='assets/images/products/premium-body-care-set.jpg', secondary_image='assets/images/products/premium-body-care-set-2.jpg' WHERE name='Premium Body Care Set';
UPDATE products SET main_image='assets/images/products/fragrance-gift-set.jpg', secondary_image='assets/images/products/fragrance-gift-set-2.jpg' WHERE name='Fragrance Gift Set';
UPDATE products SET main_image='assets/images/products/premium-coffee-mug.jpg', secondary_image='assets/images/products/premium-coffee-mug-2.jpg' WHERE name='Premium Coffee Mug';
UPDATE products SET main_image='assets/images/products/scented-candle.jpg', secondary_image='assets/images/products/scented-candle-2.jpg' WHERE name='Scented Candle';
UPDATE products SET main_image='assets/images/products/desk-organizer.jpg', secondary_image='assets/images/products/desk-organizer-2.jpg' WHERE name='Desk Organizer';
COMMIT;

