<?php $page_title='Dashboard';require 'includes/header.php';
$revenue=(float)$pdo->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE order_status<>'cancelled'")->fetchColumn();
$orders=(int)$pdo->query("SELECT COUNT(*) FROM orders")->fetchColumn();$pending=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE order_status='pending'")->fetchColumn();
$processing=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE order_status='processing'")->fetchColumn();$shipped=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE order_status='shipped'")->fetchColumn();$delivered=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE order_status='delivered'")->fetchColumn();$cancelled=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE order_status='cancelled'")->fetchColumn();
$products=(int)$pdo->query("SELECT COUNT(*) FROM products")->fetchColumn();$active=(int)$pdo->query("SELECT COUNT(*) FROM products WHERE status='active'")->fetchColumn();$out=(int)$pdo->query("SELECT COUNT(*) FROM products WHERE stock=0")->fetchColumn();$low=(int)$pdo->query("SELECT COUNT(*) FROM products WHERE status='active' AND stock<=5")->fetchColumn();$customers=(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='customer'")->fetchColumn();$admins=(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='admin'")->fetchColumn();$wish=(int)$pdo->query("SELECT COUNT(*) FROM wishlist")->fetchColumn();$msgs=(int)$pdo->query("SELECT COUNT(*) FROM contact_messages WHERE is_read=0")->fetchColumn();
$today=(float)$pdo->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE order_status<>'cancelled' AND DATE(created_at)=CURDATE()")->fetchColumn();$week=(float)$pdo->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE order_status<>'cancelled' AND created_at>=DATE_SUB(NOW(),INTERVAL 7 DAY)")->fetchColumn();$month=(float)$pdo->query("SELECT COALESCE(SUM(total),0) FROM orders WHERE order_status<>'cancelled' AND YEAR(created_at)=YEAR(CURDATE()) AND MONTH(created_at)=MONTH(CURDATE())")->fetchColumn();
$recent=$pdo->query("SELECT * FROM orders ORDER BY created_at DESC LIMIT 10")->fetchAll();$rc=$pdo->query("SELECT u.*,COUNT(o.id) orders_count FROM users u LEFT JOIN orders o ON o.user_id=u.id WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC LIMIT 6")->fetchAll();
$top=$pdo->query("SELECT oi.product_name,SUM(oi.quantity) sold,SUM(oi.subtotal) revenue FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.order_status<>'cancelled' GROUP BY oi.product_id,oi.product_name ORDER BY sold DESC LIMIT 5")->fetchAll();
?>
<div class="page-head"><div><h1>Dashboard</h1><p>Real-time store performance from MySQL.</p></div><a class="btn" href="orders.php">View orders</a></div>
<?php if($low):?><div class="alert"><strong><?=$low?> products</strong> are low on stock. <a href="inventory.php?filter=low">Review inventory →</a></div><?php endif;?>
<div class="cards"><?php foreach([['Total Revenue',money($revenue)],['Total Orders',$orders],['Pending Orders',$pending],['Processing',$processing],['Shipped',$shipped],['Delivered',$delivered],['Cancelled',$cancelled],['Products',$products],['Active Products',$active],['Out of Stock',$out],['Low Stock',$low],['Customers',$customers],['Admins',$admins],['Wishlist Items',$wish],['Unread Messages',$msgs]] as $x):?><div class="stat"><div class="label"><?=$x[0]?></div><div class="num"><?=$x[1]?></div></div><?php endforeach;?></div>
<div class="grid-2"><div class="panel"><div class="panel-head"><h2>Sales snapshot</h2><a href="analytics.php">Analytics →</a></div><div class="mini-grid"><div class="mini"><small>Today</small><b><?=money($today)?></b></div><div class="mini"><small>Last 7 days</small><b><?=money($week)?></b></div><div class="mini"><small>This month</small><b><?=money($month)?></b></div></div></div><div class="panel"><div class="panel-head"><h2>Top products</h2></div><?php foreach($top as $t):?><div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee"><span><?=e($t['product_name'])?></span><b><?=$t['sold']?></b></div><?php endforeach;?></div></div>
<div class="panel" style="margin-top:18px"><div class="panel-head"><h2>Recent orders</h2><a href="orders.php">All orders →</a></div><div class="table-wrap"><table><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th><th></th></tr><?php foreach($recent as $o):?><tr><td>#<?=$o['id']?></td><td><?=e($o['customer_name'])?></td><td><?=money((float)$o['total'])?></td><td><?=e(strtoupper($o['payment_method']))?></td><td><span class="badge <?=e($o['order_status'])?>"><?=e(ucfirst($o['order_status']))?></span></td><td><?=date('M d, Y',strtotime($o['created_at']))?></td><td><a href="order-details.php?id=<?=$o['id']?>">View</a></td></tr><?php endforeach;?></table></div></div>
<div class="panel" style="margin-top:18px"><div class="panel-head"><h2>Recent customers</h2><a href="customers.php">All customers →</a></div><div class="table-wrap"><table><tr><th>Name</th><th>Email</th><th>Registered</th><th>Orders</th></tr><?php foreach($rc as $c):?><tr><td><?=e($c['name'])?></td><td><?=e($c['email'])?></td><td><?=date('M d, Y',strtotime($c['created_at']))?></td><td><?=$c['orders_count']?></td></tr><?php endforeach;?></table></div></div>
<?php require 'includes/footer.php';?>
